version: '3.8'

services:
  backend:
    build: .
    container_name: resourcify-backend
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/skillswap_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1212
    depends_on:
      - mysql
    networks:
      - resourcify-net

  frontend:
    build: ./frontend
    container_name: resourcify-frontend
    ports:
      - "3000:80"
    networks:
      - resourcify-net

  mysql:
    image: mysql:8.0
    container_name: resourcify-db
    environment:
      MYSQL_ROOT_PASSWORD: 1212
      MYSQL_DATABASE: skillswap_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - resourcify-net

networks:
  resourcify-net:
    driver: bridge

volumes:
  mysql_data:
